# Generated by Django 4.1.6 on 2023-03-12 03:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_de_modificacao', models.DateField(auto_now=True, verbose_name='Data de Modificação')),
                ('produto_em_estoque', models.CharField(max_length=54, verbose_name='Produto em Estoque')),
                ('preco_de_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Preço de Venda')),
                ('preco_de_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Preço de Compra')),
                ('quantidade_em_estoque', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Quantidade em Estoque')),
            ],
            options={
                'ordering': ['produto_em_estoque'],
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_de_modificacao', models.DateField(auto_now=True, verbose_name='Data de Modificação')),
                ('data_da_venda', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantidade_vendida', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Quantidade Vendida')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estoque')),
            ],
            options={
                'ordering': ['data_da_venda'],
            },
        ),
    ]
