# Generated by Django 4.1.6 on 2023-02-14 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_de_modificacao', models.DateField(auto_now=True, verbose_name='Data de Modificação')),
                ('produto_em_estoque', models.CharField(max_length=54, verbose_name='Produto em Estoque')),
                ('preco_de_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Preço de Venda')),
                ('preco_de_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Preço de Compra')),
                ('quantidade_em_estoque', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Quantidade em Estoque')),
            ],
            options={
                'ordering': ['produto_em_estoque'],
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_de_modificacao', models.DateField(auto_now=True, verbose_name='Data de Modificação')),
                ('data_da_venda', models.DateTimeField(auto_now_add=True)),
                ('quantidade_vendida', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Quantidade Vendida')),
                ('quantidade_vendida2', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Quantidade Vendida 2')),
                ('quantidade_vendida3', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Quantidade Vendida 3')),
                ('quantidade_vendida4', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Quantidade Vendida 4')),
                ('quantidade_vendida5', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Quantidade Vendida 5')),
                ('quantidade_vendida6', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Quantidade Vendida 6')),
                ('quantidade_vendida7', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Quantidade Vendida 7')),
                ('quantidade_vendida8', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Quantidade Vendida 8')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estoque')),
                ('produto2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produto_2', to='core.estoque')),
                ('produto3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produto_3', to='core.estoque')),
                ('produto4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produto_4', to='core.estoque')),
                ('produto5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produto_5', to='core.estoque')),
                ('produto6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produto_6', to='core.estoque')),
                ('produto7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produto_7', to='core.estoque')),
                ('produto8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produto_8', to='core.estoque')),
            ],
            options={
                'ordering': ['produto'],
            },
        ),
    ]
