# Generated by Django 4.1.6 on 2023-02-25 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'ordering': ['data_da_venda']},
        ),
    ]
