# Generated by Django 4.1.6 on 2023-02-26 00:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_venda_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_da_venda',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
